apache/openwhisk-runtime-php

- README.md
- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- core/php7.3Action/build.gradle
- core/php7.3Action/compile
- core/php7.3Action/composer.json
- core/php7.3Action/php.ini
- core/php7.3Action/runner.php
- tests/src/test/scala/runtime/actionContainers/Php71ActionContainerTests.scala
- tests/src/test/scala/runtime/actionContainers/Php72ActionContainerTests.scala
- tests/src/test/scala/runtime/actionContainers/Php73ActionContainerTests.scala
- tests/src/test/scala/runtime/actionContainers/Php7ActionContainerTests.scala
- tools/travis/build.sh
PHP7.3 support for when it releases in early December.
This runtime uses the Go runtime's ActionProxy as the front end. This speeds things up nicely!
However, it also means that the detailed error reporting for invalid
data being uploaded to /init is not possible as this is handled by the
proxy. As a result, the specific tests that this affects have been
moved to the PHP 7.1 and 7.2 test classes.
Also, it's not possible to send back specific error messages for output
with the action proxy, so the fatal error test no longer checks for the
specific error text.
> PHP 7.3 runtime

- core/php7.1Action/CHANGELOG.md
- core/php7.1Action/Dockerfile
- core/php7.2Action/CHANGELOG.md
- core/php7.2Action/Dockerfile
- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- Update openwhisk/action-php-v7.3 runtime to php 7.3.3 (security fixes, see https://www.php.net/).
- Update openwhisk/action-php-v7.3 to actionloop 42fd5e6 (see https://github.com/apache/incubator-openwhisk-runtime-go).
- Update openwhisk/action-php-v7.2 runtime to php 7.2.16 (security fixes, see https://www.php.net/).
- Update openwhisk/action-php-v7.1 runtime to php 7.1.27 (security fixes, see https://www.php.net/)..
> Update to php7.1.27, 7.2.16 and 7.3.3.

- core/php7.3Action/Dockerfile
Replaces the docker image with the released source to build the proxy
> use released sources to build actionloop proxy

- core/php7.3Action/Dockerfile
The release tag of the actionloop (https://github.com/apache/incubator-openwhisk-runtime-go) is set to '1.11@1.13.0-incubating'. Before it was 'golang1.11@v1.13.0-incubating'. This causes the travis build to fail.
Adjusted the Dockerfile to use the new value to unblock the travis build.
> Adapt to current actionloop release tag.

- core/php7.1Action/CHANGELOG.md
- core/php7.1Action/Dockerfile
- core/php7.2Action/CHANGELOG.md
- core/php7.2Action/Dockerfile
- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
* The new versions contain bug fixes and security fixes.
I hope I updated the CHANGELOG.md files correctly. Feel free to leave a message if it should look different :-).
> Bump php runtimes to version 7.1.29, 7.2.19 and 7.3.5.

- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
Adding the database driver for mongodb to the php:7.3 runtime.
The mongodb is a very popular database. And since it is not possible to add the php extensions into the php actions themselves, it makes sense to have it in the runtime image. The same approach as for the other database drivers that are already included.
Feel free to add your comments :-).
> Add mongodb driver for php:7.3 runtime.

- core/php7.3Action/Dockerfile
* Current MongoDB driver does not support ssl/tls connections. It terminates the connection request with a MongoDB exception: `The "SCRAM-SHA-1" authentication mechanism requires libmongoc built with --enable-ssl`.
Adding the libssl-dev package allows the mongodb driver build to automatically detect this and enables ssl/tls connections.
> Add libssl-dev to support mongodb ssl/tls connections.

- .travis.yml
- core/php7.1Action/CHANGELOG.md
- core/php7.1Action/router.php
- core/php7.2Action/CHANGELOG.md
- core/php7.2Action/router.php
- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- core/php7.3Action/runner.php
- tests/src/test/scala/runtime/actionContainers/Php7ActionContainerTests.scala
The parameters need to be set up as environment variables so that
getenv() can retrieve them too.
Also closes #73.
> Add parameters as proper environment variables

- core/php7.2Action/CHANGELOG.md
- core/php7.2Action/Dockerfile
- core/php7.2Action/composer.json
- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- core/php7.3Action/composer.json
Bring the PHP 7.2 and 7.3 runtimes up to date.
* PHP 7.2.25
* PHP 7.3.12
* guzzlehttp/guzzle to 6.5.0
* ramsey/uuid to 3.9.1  
No B/C breaks.
> Update PHP & library versions for 7.2 & 7.3

- .travis.yml
- README.md
- core/php7.4Action/CHANGELOG.md
- core/php7.4Action/Dockerfile
- core/php7.4Action/build.gradle
- core/php7.4Action/compile
- core/php7.4Action/composer.json
- core/php7.4Action/php.ini
- core/php7.4Action/runner.php
- tests/src/test/scala/runtime/actionContainers/Php74ActionContainerTests.scala
Add a runtime for PHP 7.4. 
No logic, PHP extension or composer package changes from the 7.3 runtime.
Note that this PR builds on #77.
> PHP 7.4 runtime

- core/php7.2Action/Dockerfile
- core/php7.3Action/Dockerfile
- core/php7.4Action/Dockerfile
This PR updates the PHP runtime docker images to pick up the latest security fixes.
> Update php docker images to pick up security fixes

- core/php7.2Action/Dockerfile
- core/php7.3Action/Dockerfile
- core/php7.4Action/Dockerfile
Update PHP runtimes to 
* 7.2.27
* 7.3.14
* 7.4.2
to consume security updates
> Consume more PHP security updates

- core/php7.2Action/Dockerfile
- core/php7.3Action/Dockerfile
- core/php7.4Action/Dockerfile
Upgrade PHP runtimes to
~~7.4.6~~ (reverted due to [PHP Bug 79600](https://bugs.php.net/bug.php?id=79600))
7.3.18
7.2.31
> Updgrade PHP base images to gather security fixes

- NOTICE.txt
- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- core/php7.3Action/composer.json
- core/php7.4Action/CHANGELOG.md
- core/php7.4Action/Dockerfile
- core/php7.4Action/composer.json
- core/php8.0Action/CHANGELOG.md
- core/php8.0Action/Dockerfile
In preparation for 1.16.0, I've updated to use the latest PHP versions along with the latest versions of our composer dependencies.
Also updated the CHANGELOG for 1.6.0 and the NOTICE to 2021.
> Update dependencies, CHANGELOG and NOTICE for 1.16.0

- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- core/php7.4Action/CHANGELOG.md
- core/php7.4Action/Dockerfile
- core/php8.0Action/CHANGELOG.md
- core/php8.0Action/Dockerfile
Update to 8.0.11, 7.4.25 and 7.3.32
Since there is no 7.3 image that is based on Debian "stretch" anymore (7.3.29 was the last one) , 
the base image for 7.3 is changed to Debian "buster"
> Update PHP releases to gather fixes

- core/php7.3Action/CHANGELOG.md
- core/php7.3Action/Dockerfile
- core/php7.4Action/CHANGELOG.md
- core/php7.4Action/Dockerfile
- core/php8.0Action/CHANGELOG.md
- core/php8.0Action/Dockerfile
Update PHP:7.4 version from 7.4.25-cli-buster to 7.4.26-cli-buster
to provide security fix for certain XML parsing functions
> Update PHP version to 7.4.26

- core/php7.4Action/Dockerfile
- core/php8.0Action/Dockerfile
This is for convenience so customers can package their actions inside of the runtime.
> Install Zip

- core/php7.4Action/Dockerfile
- core/php8.0Action/Dockerfile
- tests/src/test/scala/runtime/actionContainers/Php7ActionContainerTests.scala
Depend on below prs: 
- https://github.com/apache/openwhisk/pull/5290 (already merged)
- https://github.com/apache/openwhisk-runtime-go/pull/170 (already merged)
> Support array result include sequence action

- .travis.yml
This bings the machines to the build VM to a more up to date Ubuntu version which should also reduce the risk of loosing support for the version and use openjdk11
> Update travis build vm dist form xenial to focal 

- core/php8.0Action/Dockerfile
- core/php8.1Action/Dockerfile
- Add 'apt-get upgrade' to always update the already installed packages with the latest security fixes in case they are not already part of the parent image. Sometimes the updates on the parent image take some time and with this explicit upgrade, we are on the save side.
> Always install latest security fixes (8.0,8.1).
